### ISSUE TITLE
Support for modules?

### ISSUE THREAD

**Issue by elasmojs** [SkylerLipthay/ducc#22]
Is there support for modules already available?

**Comment by SkylerLipthay** [comment]
Modules are not implemented in any form in ducc as of yet. The solution for modules is [left fairly open by Duktape](https://duktape.org/guide.html#modules.1). So if you have a suggested interface I'd be interested in hearing about it!

**Comment by elasmojs** [comment]
Hi, @SkylerLipthay thank you appreciate the quick response. I will go over the suggested reference.
