### ISSUE TITLE
Can we mutate userdata entry inside a JS invoked function?

### ISSUE THREAD

**Issue by elasmojs** [SkylerLipthay/ducc#23]
@SkylerLipthay Hi! Is there a way to set userdata inside a JS invoked function. Thanks

```
fn set_name(inv: Invocation) -> Result<Value, DuccError>{
    let this = inv.this.as_object().unwrap();
    let engine = inv.ducc;

    engine.set_user_data("name", "Ducc Rocks!");
    //Compile error here: cannot borrow `*engine` as mutable, as it is behind a `&` reference

    return Ok(Value::Boolean(true));
}
```

**Comment by SkylerLipthay** [comment]
Unfortunately it's necessary to keep the borrow rules as they are, but you can work around this by using interior mutability:

```rust
use std::cell::RefCell;
ducc.set_user_data("name", RefCell::new("abc123".to_string()));
// Later in a function:
inv.ducc.get_user_data("name").unwrap().replace_with(|string| string.push_str("def456"));
```

Do you think this pattern can work for you?

**Comment by elasmojs** [comment]
Thank you for the quick response, i tried it, i get the following error

cannot infer type for type parameter `T` declared on the associated function `get_user_data`

also would this be possible if the user data was a Hashmap too?

**Comment by SkylerLipthay** [comment]
Oh, use `get_user_data::<RefCell<String>>("name")`. Yes, you can use this pattern with any sort of data.

You can learn more about [interior mutability from the Rust book](https://doc.rust-lang.org/book/ch15-05-interior-mutability.html), where they have a complex example of using a `RefCell<Vec<String>>`. Which is perhaps similar to your use case with the `HashMap`.

**Comment by elasmojs** [comment]
Thanks a ton! This works! :-)
